### ISSUE TITLE
Name reported as available but can't be used in npm publish

### ISSUE THREAD

**Issue by astur** [sindresorhus/npm-name-cli#10] opened 2018-05-24 09:04 UTC
I had try to publish on npm package named 'while-true'. npm answered me:
```bash
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! Package name too similar to existing packages; try renaming your package to '@astur/while-true' and publishing with 'npm publish --access=public' instead : while-true
```

And it was first moment when I found that something wrong with name 'while-true'. This name is reported by npm-name as available:
```bash
~ $ npm-name while-true
✔ while-true is available
```

It will be better if npm-name will say something like this:
```bash
⚠ while-true is free but available
```

...or like this:
```bash
⚠ while-true is too similar to existing package whiletrue
```

**Comment by sindresorhus** [comment] 2018-05-24 09:07
Duplicate of #7

**Closed by sindresorhus** 2018-05-24 09:07 UTC
