### ISSUE TITLE
Error on some names

### ISSUE THREAD

**Issue by astur** [sindresorhus/npm-name-cli#9] opened 2018-05-23 12:54 UTC
HTTPError throws when checking some package names via this cli-package. Like this:

```bash
~ $ npm-name f
HTTPError: Response code 404 (Not Found)
    at stream.catch.then.data (/usr/local/lib/node_modules/npm-name-cli/node_modules/squatter/node_modules/got/index.js:182:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

[f](https://www.npmjs.com/package/f) is real npm package.

When using API from [npm-name](https://github.com/sindresorhus/npm-name) it will be all right for this package:

```js
const nn = require('npm-name');
await nn('f') // false
```

I thing it is a bug.

**Comment by sindresorhus** [comment] 2018-05-23 14:47
The error is coming from https://github.com/sholladay/squatter

// @sholladay

**Comment by sholladay** [comment] 2018-05-23 16:29
Thanks, I am able to reproduce this. Seems to be due to changes to the npm registry. Specifically, the call we make at [has-binary-or-dependent.js#L16-L28](https://github.com/sholladay/squatter/blob/6f1e23beb5c21a943f98f4db0717012aba09b29a/lib/has-binary-or-dependent.js#L16-L28) is now failing for all packages. The reason you only see it for some packages in the CLI is because we short-circuit the logic and don't run that code if we don't need it, which is the case for some packages.

I ran the `squatter` tests and the [integration test for `hasBinaryOrDependent()`](https://github.com/sholladay/squatter/blob/6f1e23beb5c21a943f98f4db0717012aba09b29a/test.js#L96-L119) is failing where it was previously passing.

The error output from the `squatter` tests shows the full `GotError`:
```js
HTTPError (GotError) {
  headers: {
    'accept-ranges': 'bytes',
    age: '0',
    'cache-control': 'max-age=0',
    connection: 'close',
    date: 'Wed, 23 May 2018 16:01:32 GMT',
    'npm-notice': 'this endpoint is deprecated',
    'transfer-encoding': 'chunked',
    via: '1.1 varnish',
    'x-cache': 'MISS',
    'x-cache-hits': '0',
    'x-served-by': 'cache-bos8228-BOS',
    'x-timer': 'S1527091292.376027,VS0,VE366',
  },
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/-/_view/dependedUpon?group_level=2&startkey=%5B%22rawr%22%5D&endkey=%5B%22rawr%22%2C%7B%7D%5D&stale=update_after&skip=0&limit=1000',
  protocol: 'https:',
  statusCode: 404,
  statusMessage: 'Not Found',
  url: 'https://registry.npmjs.org/-/_view/dependedUpon?group_level=2&startkey=%5B%22rawr%22%5D&endkey=%5B%22rawr%22%2C%7B%7D%5D&stale=update_after&skip=0&limit=1000',
  message: 'Response code 404 (Not Found)',
}
```

The thing that catches my eye is that `npm-notice` header:
```
'npm-notice': 'this endpoint is deprecated'
```

I guess this is a hard deprecation. 😞 

Anyone know if there is a replacement? I filed https://github.com/npm/registry/issues/231 back when I first released `squatter`, asking for an alternative. I'm not aware of any movement on that. @zeke's [dependent-counts](https://github.com/nice-registry/dependent-counts) package is the best solution I know of, but it is out of date and the install size is 11MB.

**Comment by zeke** [comment] 2018-05-23 19:46
The [all-the-package-names](https://ghub.io/all-the-package-names) package is updated daily by a bot. It's not up-to-the-minute accurate, but will be adequate for most cases:

```
npx all-the-package-names | egrep '^foo'
```

See also [available](https://ghub.io/available) by @feross.

**Comment by zeke** [comment] 2018-05-23 20:33
Yeah `dependent-counts` is in dire need of upkeep and automation.

Registry folks you may want to reach out to: 

- https://github.com/ceejbot
- https://github.com/bcoe
- https://github.com/soldair
- https://github.com/mmalecki

**Comment by sholladay** [comment] 2018-05-24 00:37
I reached out to Benjamin Coe on Twitter and he [replied](https://twitter.com/BenjaminCoe/status/999415441008177153) that the endpoint being used here has not knowingly been deprecated. So this is likely just a regression that will (hopefully) be fixed soon.

I'll give them some time to fix it and in the meantime, I'll think about ideas for offline fallbacks to improve the UX going forward.

**Comment by sholladay** [comment] 2018-05-24 16:34
Neat idea! Seems like a reasonable workaround for now. I'll open a couple of issues with improvement ideas and look into including it in a patch release.

**Comment by zeke** [comment] 2018-05-24 19:18
> check-npm-dependents

good idea, @astur.

Is anyone else sad that it's 2018, npm Inc has been a funded company for 5 years, and there's still no API for this kind of thing? Seems ridiculous that we have to scrap the website for this info.

**Comment by sindresorhus** [comment] 2018-08-20 05:00
@sholladay Can you use that package and release a new version of `squatter` so we can close this issue?

**Comment by sholladay** [comment] 2018-08-20 08:54
I have fixed this in `squatter@0.2.0` (release notes [here](https://github.com/sholladay/squatter/releases/tag/v0.2.0)). Note that I had to release it as a breaking change, because [scra](https://github.com/astur/scra) (a subdependency of `check-npm-dependents`) requires Node 8+, whereas `squatter` previously supported Node 7.6+. That shouldn't be a problem for anyone since Node 7 is EOL and `npm-name-cli` is already on 8+, but we'll have to upgrade manually here in `npm-name-cli`.

I opened a PR with the upgrade: https://github.com/sindresorhus/npm-name-cli/pull/13

Unrelated side note: `scra` relies on a deprecated version of `socks`, so it prints warnings to the console on installation. Would be great if we could clean that up. @astur.

**Comment by astur** [comment] 2018-08-20 09:00
@sholladay No problem, I can change `scra` to `got` if you want it.

**Comment by sholladay** [comment] 2018-08-20 09:06
Also, in case anyone wonders why we were using a CouchDB view in the first place, it was [officially supported](https://github.com/npm/registry/blob/71260fc413acdc43e246bdf83091fcfb87e71ba3/docs/COUCHDB.md#background)...

> Because npm cares deeply about backwards compatibility, as the npm regsitry grows out of its CouchApp and CouchDB origins, all of the original endpoints and functionality of the original API will continue to be supported.

😞

**Comment by astur** [comment] 2018-08-20 09:47
@sholladay Now `npm-name-cli` uses `got` instead `scra`. Does it works well on your task?

**Closed** 2018-08-20 09:47 UTC
Labels: bug
